version: "3.9"
services:
  attacker:
    image: kalilinux/kali-rolling
    command: tail -f /dev/null # Command to keep the container running after setup is finished
    container_name: attacker_scenario1
    networks:
      - public
  metasploitable:
    build: ../metasploitable
    image: ais_metasploitable:latest
    container_name: metasploitable_scenario1
    networks:
      - public
      - backend-services
    command: tail -f /dev/null # Command to keep the container running after setup is finished
  api:
    build: ../api
    image: ais_api:latest
    container_name: api_scenario1
    expose:
      - "3000"
    networks:
      - calculator
      - backend-services
  website:
    build: ../website
    image: ais_website:latest
    container_name: website_scenario1
    ports: 
      - "8080:80"
    networks:
      - calculator
networks:
  calculator:
    driver: bridge # Represents a seperate network for a service. In this case a calculator
  backend-services:
    driver: bridge # Represents a hypothetical network that contains a range of backend services
  public:
    driver: bridge # Represents public access