version: "3.9"
services:
  attacker:
    image: kalilinux/kali-rolling
    command: tail -f /dev/null # Command to keep the container running after setup is finished
    container_name: attacker
  metasploitable:
    build: ../metasploitable
    image: ais_metasploitable:latest
    container_name: metasploitable
    command: tail -f /dev/null # Command to keep the container running after setup is finished
  api:
    build: ../api
    image: ais_api:latest
    container_name: api
    expose:
      - "3000"
  website:
    build: ../website
    image: ais_website:latest
    container_name: website
    ports: 
      - "8080:80"