version: "3.9"
services:
  api:
    build: ../api
    container_name: api
    expose:
      - "3000"
    networks:
      - my-net
  website:
    build: ../website
    container_name: website
    ports: 
      - "8080:80"
    networks:
      - my-net
networks:
  my-net:
    driver: bridge